# Generated by Django 2.2.24 on 2021-12-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='multireligionstodet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='multireligionval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='multireligionvalsystem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='orgnr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trossamfund',
            field=models.TextField(blank=True, null=True),
        ),
    ]
